baseURL = "https://birros.github.io/"
theme = "hugo-bootstrap"
title = "Birros"
DefaultContentLanguage = "fr"

paginate = 3
paginatePath = "page"

[params]
mainSections = [ "journal" ]
author = "Birros"
date_format = "2006-01-02"

[Languages.en]
languageName = "English"
copyright = "This content is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

[Languages.fr]
languageName = "Français"
copyright = "Ce contenu est sous licence Creative Commons Attribution-ShareAlike 4.0 International License."
